# -- Instalando e carregando o Tidyverse e Scales --
```{r}
# install.packages("tidyverse")
library(tidyverse)
# install.packages("scales")
library(scales)
```

# -- Pegando os dados da população brasileira dos arquivos .csv --
```{r}
dados = list(
  deficiencias = read_csv2("../data/original/censo_2022_deficiencia_e_autismo.csv"),
  alfabetizacao = read_csv2("../data/original/censo_2022_alfabetizacao.csv"),
  crescimento = read_csv2("../data/original/censo_2022_crescimento_pop.csv"),
  nomes = read_csv2("../data/original/censo_2022_nomes_populares.csv"),
  transporte = read_csv2("../data/original/censo_2022_meios_transporte.csv"),
  cor_raca = read_csv2("../data/original/censo_2022_população_cor_raca.csv"),
  religiao = read_csv2("../data/original/censo_2022_religiao.csv"),
  piramide = read_csv2("../data/original/censo_2022_piramide_etaria.csv"),
  sexo = read_csv2("../data/original/censo_2022_populacao_sexo.csv"),
  favelas = read_csv2("../data/original/censo_2022_populacao_favelas.csv")
)
```

# -- Dados de referência --
```{r}
refs = list(
  alfabetizacao = read_csv("../data/refs/alfabetizacao_paises.csv"),
  deficiencia = read_csv2("../data/refs/censo_2010_deficiencia.csv"),
  crescimento = read_csv2("../data/refs/crescimento_pop.csv")
)
```

# -- Confirmando tipos --
```{r}
glimpse(dados$deficiencias)
glimpse(dados$alfabetizacao)
glimpse(dados$crescimento)
glimpse(dados$nomes)
glimpse(dados$transporte)
glimpse(dados$cor_raca)
glimpse(dados$religiao)
glimpse(dados$piramide)
glimpse(dados$sexo)
glimpse(dados$favelas)
```

# -- Analisando nomes mais populares --
```{r}
plot_nomes_populares = dados$nomes %>%
  ggplot(aes(x=reorder(Nome,Pessoas), y=Pessoas, fill=Nome)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",")
  ) + scale_fill_brewer(palette="Paired") + labs(
    title = "Nomes mais populares",
    y = "Quantidade pessoas",
    x = "Nomes"
  ) + theme(
    legend.position = "none"
  )
```

# -- Analisando alfabetização --
```{r}
plot_alfabetizados = dados$alfabetizacao %>%
  ggplot(aes(x=Situação, y=Percentual, fill=Situação)) +
  geom_bar(stat="identity") + scale_fill_brewer(palette="Set3") + theme(
    legend.position = "none"
  ) + labs(
    title = "Percentual de alfabetizados no Brasil"
  )

alfabetizados_brasil <- dados$alfabetizacao %>%
  filter(Situação == "Alfabetizados",
         `Recorte Geográfico` == "Brasil") %>%
  select(Percentual, `Recorte Geográfico`)

comparacao = bind_rows(alfabetizados_brasil, refs$alfabetizacao)

comparacao %>%
  ggplot(aes(x=reorder(`Recorte Geográfico`, Percentual), y=Percentual,
             fill=`Recorte Geográfico`,
             label=paste0(Percentual, "%"))) +
  geom_bar(stat="identity") +
  geom_label(
    size=3,
    alpha=0,
    label.size=0,
    label.padding = unit(0.25, "lines"),
    color="black",
    family="sans",
    fontface="bold",
    nudge_y=-4
  ) +
  labs(x = NULL, 
       y = "Percentual (%)", 
       title = "Percentual de alfabetização por países") +
  scale_fill_brewer(palette="Set3") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position="none"
  ) 
```

# -- Comparando percentual de pessoas com deficiência do Censo 2010 vs 2022 --
```{r}
dados$deficiencias
refs$deficiencia
```

# -- Analisando crescimento populacional --
```{r}

unique(dados$crescimento$`Ano da pesquisa`)

dados$crescimento %>%
  ggplot(aes(x=`Ano da pesquisa`,y=`População(pessoas)`, group=1)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",")
  ) +
  labs(
    title = "Crescimento da população brasileira ao longo dos censos",
    x = "Ano",
    y = "População"
  ) +
  theme_minimal()

comparacao_cresc = bind_rows(dados$crescimento, refs$crescimento)

crescimento_linhas = comparacao_cresc %>%
  ggplot(aes(x=`Ano da pesquisa`, y=`População(pessoas)`,color=`Recorte Geográfico`)) +
  geom_line() + geom_point() +
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",") 
  ) + theme_minimal()

crescimento_linhas
```
## -- Analisando sexos/pirâmide etária --
```{r}
dados$sexo %>%
  ggplot(aes(x=Sexo, y=`População(pessoas)`, fill=Sexo)) +
  geom_col() +
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",") 
  )
dados$piramide %>%
  mutate(
    `Grupo de idade` = fct_rev(fct_inorder(`Grupo de idade`))
    ) %>%
  ggplot(aes(x=`Grupo de idade`)) +
  geom_col(aes(y=`População feminina(pessoas)`, fill="Feminino"), alpha=0.5) + 
  geom_col(aes(y=`População masculina(pessoas)`, fill="Masculino"), alpha=0.5) + 
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",") 
  ) + 
  scale_fill_manual(values= c(
    "Feminino"="blue",
    "Masculino"="red" 
  )) + coord_flip() +
  labs(
    title = "Pirâmide etária comparando masculino e feminino",
    fill="Gêneros",
    y="População"
  )

```