# -- Instalando e carregando o Tidyverse e Scales --
```{r}
# install.packages("tidyverse")
library(tidyverse)
# install.packages("scales")
library(scales)
```

# -- Capturando os dados tratados --
```{r}
dados = list(
  nomes = read_csv2("../data/original/censo_2022_nomes_populares.csv"),
  religiao = read_csv("../data/clean/religiao_tratado.csv"),
  alfabetizacao = read_csv("../data/clean/alfabetizacao_tratado.csv"),
  crescimento = read_csv("../data/clean/crescimento_tratado.csv"),
  sexo = read_csv2("../data/original/censo_2022_populacao_sexo.csv"),
  piramide = read_csv("../data/clean/piramide_tratado.csv"),
  favelas = read_csv("../data/clean/favelas_tratado.csv")
  )
```

# -- Capturando as comparações utilizadas --
```{r}
comp = list(
  alfabetizacao = read_csv("../data/clean/comparacao_alfabetizacao.csv"),
  crescimento = read_csv("../data/clean/comparacao_crescimento.csv"),
  favelas = read_csv("../data/clean/comparar_favelas.csv"),
  favelas_alternativo = read_csv("../data/clean/favelas_alternativo_tratado.csv")
)
```

# -- Analisando nomes mais populares --
```{r}
plot_nomes_populares = dados$nomes %>%
  ggplot(aes(x=reorder(Nome,Pessoas), y=Pessoas, fill=Nome)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",")
  ) + scale_fill_brewer(palette="Paired") + labs(
    title = "Nomes mais populares",
    y = "Quantidade pessoas",
    x = "Nomes"
  ) + theme(
    legend.position = "none"
  )
plot_nomes_populares
```

# -- Plotando religiosidade --
```{r}
plot_religiosidade = dados$religiao %>%
  ggplot(aes(x=reorder(Religião, `População (pessoas)`),
             y=`População (pessoas)`, fill=Religião)) +
  geom_col() + scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",")) + coord_flip() + theme(legend.position="none")

plot_religiosidade
```

# -- Analisando alfabetização --
```{r}
plot_alfabetizados = dados$alfabetizacao %>%
  ggplot(aes(x=Situação, y=Percentual, fill=Situação)) +
  geom_bar(stat="identity") + scale_fill_brewer(palette="Set3") + theme(
    legend.position = "none"
  ) + labs(
    title = "Percentual de alfabetizados no Brasil"
  )

plot_comp_alfabetizados = comp$alfabetizacao %>%
  ggplot(aes(x=reorder(País, Percentual), y=Percentual,
             fill=País,
             label=paste0(Percentual, "%"))) +
  geom_bar(stat="identity") +
  geom_label(
    size=3,
    alpha=0,
    label.size=0,
    label.padding = unit(0.25, "lines"),
    color="black",
    family="sans",
    fontface="bold",
    nudge_y=-4
  ) +
  labs(x = NULL, 
       y = "Percentual (%)", 
       title = "Percentual de alfabetização por países") +
  scale_fill_brewer(palette="Set3") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position="none"
  ) 

plot_alfabetizados
plot_comp_alfabetizados
```

# -- Crescimento --
```{r}
plot_crescimento_brasil = dados$crescimento %>%
  ggplot(aes(x=Ano,y=Quantidade, group=1)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",")
  ) +
  labs(
    title = "Crescimento da população brasileira ao longo dos censos",
    x = "Ano",
    y = "População"
  ) +
  theme_minimal()


plot_comp_crescimento = comp$crescimento %>%
  ggplot(aes(x=Ano, y=Quantidade,color=País)) +
  geom_line() + geom_point() +
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",") 
  ) + theme_minimal()

plot_crescimento_brasil
plot_comp_crescimento
```

## -- Analisando sexos/pirâmide etária --
```{r}
plot_sexo = dados$sexo %>%
  ggplot(aes(x=Sexo, y=`População(pessoas)`, fill=Sexo)) +
  geom_col() +
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",") 
  )

plot_piramide = dados$piramide %>%
  mutate(
    ordem = as.integer(str_extract(Grupo, "^\\d+")),
    Grupo = fct_reorder(Grupo, ordem)
    ) %>%
  ggplot(aes(x=Grupo)) +
  geom_col(aes(y=Feminino, fill="Feminino"), alpha=0.5) + 
  geom_col(aes(y=Masculino, fill="Masculino"), alpha=0.5) + 
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".", decimal.mark = ",") 
  ) + 
  scale_fill_manual(values= c(
    "Feminino"="blue",
    "Masculino"="red" 
  )) + coord_flip() +
  labs(
    title = "Pirâmide etária comparando masculino e feminino",
    fill="Gêneros",
    y="População"
  )

plot_sexo
plot_piramide
```

# -- Analisando população residente em favelas --
```{r}
dados$favelas
comp$favelas

plot_favelas = comp$favelas %>%
  filter(Situação=="Em favelas") %>%
  group_by(País) %>%
  ggplot(aes(x=País, 
             y=Percentual, 
             fill=País, 
             label=paste0(Percentual, "%"))) +
  geom_col() + 
    geom_label(
    size=3,
    alpha=0,
    label.size=0,
    label.padding = unit(0.25, "lines"),
    color="black",
    family="sans",
    fontface="bold",
    nudge_y=-4
  ) +
  theme(
    legend.position = "none"
  ) + labs(
    title="População residente em favelas por país (%)"
  )

plot_favelas
```

# -- Comparando favelização usando fonte alternativa --
```{r}
plot_favelas_alternativo = comp$favelas_alternativo %>%
  ggplot(aes(x=Ano, y=Percentual, color=País)) +
  geom_line() + geom_point()

plot_favelas_alternativo
```